// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe7fwDKOskAyx7ReQV3q9lRaQvl62jjyo',
    appId: '1:788690157237:web:b23d7e0664663965b388fc',
    messagingSenderId: '788690157237',
    projectId: 'emergency-app-c604b',
    authDomain: 'emergency-app-c604b.firebaseapp.com',
    storageBucket: 'emergency-app-c604b.appspot.com',
    measurementId: 'G-77BVY0483F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR5CBFaQpcFAbFn1TkADBchzC_VtDyKO8',
    appId: '1:788690157237:android:9c5213fda1711773b388fc',
    messagingSenderId: '788690157237',
    projectId: 'emergency-app-c604b',
    storageBucket: 'emergency-app-c604b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIvESZhx6ogvBEpNiwVLxrvTQYWJMrnZU',
    appId: '1:788690157237:ios:2a01a0deccab7e4db388fc',
    messagingSenderId: '788690157237',
    projectId: 'emergency-app-c604b',
    storageBucket: 'emergency-app-c604b.appspot.com',
    iosBundleId: 'com.hackathon.emergencyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIvESZhx6ogvBEpNiwVLxrvTQYWJMrnZU',
    appId: '1:788690157237:ios:6a1a94a5f0891579b388fc',
    messagingSenderId: '788690157237',
    projectId: 'emergency-app-c604b',
    storageBucket: 'emergency-app-c604b.appspot.com',
    iosBundleId: 'com.example.emergencyAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe7fwDKOskAyx7ReQV3q9lRaQvl62jjyo',
    appId: '1:788690157237:web:e41046dc29f2dedeb388fc',
    messagingSenderId: '788690157237',
    projectId: 'emergency-app-c604b',
    authDomain: 'emergency-app-c604b.firebaseapp.com',
    storageBucket: 'emergency-app-c604b.appspot.com',
    measurementId: 'G-W1ZBRLQB0Z',
  );

}